avro/src/encode.rs
avro/src/lib.rs
avro/src/reader.rs
avro/src/schema.rs
avro/src/schema_equality.rs
avro/src/types.rs
avro/src/validator.rs
avro_derive/tests/derive.rs
wasm-demo/tests/demos.rs

This PR will use Rust 2021 edition's `use abc` to replace `extern crate abc`.

chore: Use `use abc` to replace `extern crate abc`

---

Cargo.toml
avro/Cargo.toml
avro_derive/Cargo.toml
avro_test_helper/Cargo.toml
wasm-demo/Cargo.toml

This PR contains two changes:
- Update repository field to `apache/avro-rs`
- Remove [deprecated authors field](https://github.com/rust-lang/rfcs/blob/master/text/3052-optional-authors-field.md)

chore: Update repository and remove deprecated authors field

---

avro/src/error.rs
avro/src/writer.rs

Fixes #10.
This PR calls `std::io::Write::flush` on the inner `writer` of `apache_avro::Writer` at the end of `apache_avro::Writer::flush`. This ensures that the flush is propagated and the previously written bytes are fully sent.
This PR also includes a unit test that confirms `Writer::flush` now works as expected.

AVRO-4063: Call `flush` on the inner `writer` during `Writer::flush`

---

avro/src/schema.rs

Add a new method `Schema::parse_str_with_list` that can parse a root schema along with a list of named schemas.  This method can be used to parse a root union that has named schema references, for example.
This new method combines the functionality of `Schema::parse_str` with `Schema::parse_list`.
Fixes https://github.com/apache/avro-rs/issues/103

Add method `Schema::parse_str_with_list` to parse root schemas with references

---

avro/src/schema.rs

A minor enhancement to `parse_str_with_list` to return the parsed named schemata.  This is to make it easier to use with `to_avro_datum_schemata` and `from_avro_datum_schemata`, both of which take a root schema and a Vector of named schemas.
This is a follow-on PR to https://github.com/apache/avro-rs/pull/104

Minor enhancement to `parse_str_with_list`

---

avro/src/lib.rs
avro/src/reader.rs
avro/src/types.rs
avro/tests/to_from_avro_datum_schemata.rs

Add a "from" datum reader that can take reader schemata. 
Currently the `from_avro_datum_schemata` method can take writer schemata so that references in the writer schema can be resolved correctly, but it does not take reader schemata so that references in the reader schema can be resolved correctly.
I've added a new method `from_avro_datum_reader_schemata` that can take both writer and reader schemata.  (Feel free to change the name of this method)

Add a "from" datum reader that can take reader schemata

---

avro/src/schema.rs
avro/tests/schema.rs

Added independent_canonical_form, which populates types available in the schemata, so that the given schema can be encoded for PCF without the schemata.
See https://github.com/apache/avro-rs/issues/64

Added Schema::independent_canonical_form

---

deny.toml

This crate is used to generate unit tests and there is no known issue using it.

chore: Fix `cargo deny check` by allowing the usage of dtolnay/paste

---

avro/benches/serde.rs
avro/src/ser_schema.rs

This is a follow-up from my last PR: `SchemaAwareWriteSerializer` doesn't need the schema_stack field since it can make use of the call stack to track which schema it's currently using.  Making this switch makes the schema tracking a bit more consistent, whereas before, sometimes the schema_stack was used, and sometimes a new `SchemaAwareWriteSerializer` as created.  This switch also improves performance slightly, particularly when the serializer encounters union or reference values.
Changes in this PR:
- Remove schema_stack field in favor of `serialize_*_with_schema` member functions
- Benchmark tests updated to include some union fields to measure performance of `serialize_*_with_schema` logic
- Rename support classes to match SchemaAwareWriteSerializer

Remove schema_stack field from SchemaAwareWriteSerializer

---

Cargo.lock
avro/Cargo.toml
avro/src/codec.rs
avro/src/error.rs

Switch from [libflate](https://crates.io/crates/libflate) to [miniz_oxide](https://crates.io/crates/miniz_oxide) as the DEFLATE backend.
miniz_oxide is faster and more widely tested. It is the default backend for the de-facto standard [flate2](https://crates.io/crates/flate2) crate, and has 10x the amount of downloads compared to libflate.
I've taken care to preserve the same public API so that this change would be transparent to users.

Use miniz_oxide - a better DEFLATE backend

---

avro/src/error.rs
avro/src/headers.rs
avro/src/lib.rs
avro/src/reader.rs
avro/src/writer.rs

Addresses #164 
I didn't get any response when I asked about preferred designs, so I went ahead and created one that seemed reasonable to me.
I created a new Header module with a HeaderBuilder trait, then reimplemented the existing Rabin fingerprint header as a struct impling this trait, and also another one with the Glue schema header type that I used. This design should be sufficiently generic to allow for the future implementation of more header types.
I also added a new method to the GenericSingleObjectReader and GenericSingleObjectWriter to allow the creation of each object type with a HeaderBuilder instance. I then modified the existing creator methods to keep the same signature but call these new methods with the RabinFingerprintHeader struct to maintain the current behavior, and I …

Support different header types

---

avro/src/lib.rs
avro/src/writer.rs

My use case is I'm serializing large counts of individual objects to publish to google pubsub in an async setting where the "real" work being done elsewhere is so inexpensive to do that overhead dominates performance concerns.
Basically I want to use avro-rs to serialize with minimal allocation/cloning and I must not have headers or markers in the output.
Specifics you can skip:
> google's pubsub uses a stripped down version of the single record format (v1) - it is without any of the headers or markers, it only wants avro's raw binary encoding. Topics are configured with a the avro schema and the format so they are assumed when trying to publish to that topic.
> 
> The high volume makes it undesirable to construct a SpecificSingleObjectWriter per call as it clones the avro schema.
> The …

feat: Expose the capability to do headerless avro encoding with serde

---

avro/src/error.rs
avro/src/ser_schema.rs
avro/src/writer.rs

Enums are the size of their largest variants and Schema is a very large type. This also means that every AvroResult is also at least as big as the Error type.

perf: Reduce the size of Error from 256 bytes to 88 bytes

---

avro/src/schema.rs
avro/src/schema_compatibility.rs
avro/src/types.rs
avro/tests/schema.rs
avro/tests/to_from_avro_datum_schemata.rs
avro/tests/union_schema.rs

They now accept anything that can iterate over types that can be converted into strings. For example: `Vec<String>`, `&[&str]`, and `files.iter().map(std::fs::read_to_string).filter_map(Result::ok)`.

feat: Accept more inputs for `Schema::parse_(str_with)_list`

---

avro/src/lib.rs
avro/src/writer.rs

This can be useful for checking the size of the output. For example, you might want to batch values every N megabytes.
I've also added two commits, one which simplifies the doc comments and one which makes the `WriterBuilder` type public.
The alternative to `peek_inner` is doing:
- `let aw = Writer::builder().schema(schema).marker(marker).writer(writer)`
- `aw.append_ser(value)`
- `writer = aw.into_inner()`
- `writer.len()`
- `aw = Writer::append_to(schema, writer, marker)`
And this recreates the writer every time, which does a bunch of allocations.

feat: Add `get_ref` and `get_mut` methods to `Writer`

---

avro/src/writer.rs
avro/tests/to_from_avro_datum_schemata.rs
avro/tests/union_schema.rs

This brings the writer in line with standard library types like `BufWriter` and `LineWriter`.
This is a breaking change when the inner writer is `&mut W` and used later in the scope without dropping the writer or calling `into_inner` (as seen in the fixed tests).

fix: flush Writer on drop

---

avro/examples/generate_interop_data.rs
avro/src/types.rs
avro/tests/append_to_existing.rs

Error:
```
error: lifetime flowing from input to output with different syntax can be confusing
--> avro/src/types.rs:238:24
|
238 |     pub fn new(schema: &Schema) -> Option<Record> {
|                        ^^^^^^^            ------ the lifetime gets resolved as `'_`
|                        |
|                        this lifetime flows to the output
|
= note: `-D mismatched-lifetime-syntaxes` implied by `-D warnings`
= help: to override `-D warnings` add `#[allow(mismatched_lifetime_syntaxes)]`
help: one option is to remove the lifetime for references and use the anonymous lifetime for paths
|
238 |     pub fn new(schema: &Schema) -> Option<Record<'_>> {
|                                                 ++++
```

chore: Fix the build with latest nightly compiler (06.06.2025)

---

avro_derive/src/lib.rs

Improve the `AvroSchema` macro to support `#[avro(rename = "new_name")]` for enum variants.
Example:
```
enum A {
#[avro(rename = "A3")]
Item1,
}
```
will generate
```
Enum(EnumSchema { name: Name { name: "A", namespace: None }, aliases: None, doc: None, symbols: ["A3"], default: None, attributes: {} })
```

feat: Add support for rename of enum variants in AvroSchema macro

---

avro_derive/src/case.rs
avro_derive/src/lib.rs

Supports the same settings as serde. 
Because we need to have the same behavior as serde, the case conversion code was copied from serde crate.

feat: Add support for rename_all in AvroSchema macro

---

Cargo.lock
avro/Cargo.toml
avro/tests/avro-rs-219.rs

See https://github.com/akubera/bigdecimal-rs/issues/151

Fixes #219: Use `serde` as a feature for bigdecimal decimal

---

avro/src/error.rs
avro/src/types.rs

Fixes #225
Add the UnionSchema and the actual Value to the error message for easier debugging

fix: Improve the error message for unresolved union variant

---

avro/src/ser_schema.rs
avro/tests/avro-rs-226.rs

fix #226: Index-Out-Of-Bounds panic when using #[serde(skip_serializing_if=..)]

fix #226: Index-Out-Of-Bounds panic when using #[serde(skip_serializing_if=..)]

---

Cargo.lock
avro/Cargo.toml

Hi there @martin-g 👋 
Bon had a faulty lower-bound, see: https://github.com/elastio/bon/pull/336

chore(deps): Bump bon to 3.7.2
